sonar.projectKey=marcc28_AGRITWIN
sonar.organization=marcc28

sonar.sources=.

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,**/.expo/**,**/ios/Pods/**

sonar.sourceEncoding=UTF-8
